services:
  muxer:
    image: orryverducci/dabmux:latest
    build: ./muxer
    environment:
      - TZ=Europe/London
    volumes:
      - ./muxer/configuration.mux:/data/configuration.mux

  modulator:
    image: orryverducci/dabmod:latest
    build: ./modulator
    depends_on:
      - muxer
    environment:
      - MOD_RTLTCP=true
      - TZ=Europe/London
    ports:
      - 1234:1234
    volumes:
      - ./modulator/configuration.ini:/data/configuration.ini

  encoder:
    image: orryverducci/dabenc:latest
    build: ./encoder
    depends_on:
      - muxer
    environment:
      - ENC_BITRATE=48
      - ENC_MUX=tcp://muxer:9000
      - ENC_SAMPLERATE=48000
      - ENC_SOURCE=https://a1.radio.co/s5c5da6a36/listen
      - TZ=Europe/London
