FROM debian:bookworm AS builder

WORKDIR /build

RUN DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get install -y \
    automake \
    build-essential \
    git \
    libboost-system-dev \
    libcurl4-openssl-dev \
    libtool \
    libzmq3-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/Opendigitalradio/ODR-DabMux.git

RUN cd ODR-DabMux \
    && ./bootstrap.sh \
    && ./configure --prefix=/build/output

RUN cd ODR-DabMux \
    && make \
    && make install

FROM debian:bookworm

RUN DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get install -y \
    libboost-system1.74.0 \
    libcurl4 \
    libzmq5 \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /build/output/bin/odr-dabmux /usr/bin/

ENTRYPOINT ["odr-dabmux"]
