####################
# Audio builder
####################

FROM debian:bookworm-slim AS builder-audio

WORKDIR /build

RUN DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get install -y \
    automake \
    build-essential \
    git \
    libcurl4-openssl-dev \
    libgstreamer1.0-dev \
    libgstreamer-plugins-base1.0-dev \
    libtool \
    libzmq3-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/Opendigitalradio/ODR-AudioEnc.git

RUN cd ODR-AudioEnc \
    && ./bootstrap \
    && ./configure --enable-gst --prefix=/build/output

RUN cd ODR-AudioEnc \
    && make \
    && make install

####################
# PAD builder
####################

FROM debian:bookworm-slim AS builder-pad

WORKDIR /build

RUN DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get install -y \
    automake \
    build-essential \
    git \
    libtool \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/Opendigitalradio/ODR-PadEnc.git

RUN cd ODR-PadEnc \
    && ./bootstrap \
    && ./configure --prefix=/build/output

RUN cd ODR-PadEnc \
    && make \
    && make install

####################
# Runtime image
####################

FROM debian:bookworm-slim

RUN DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get install -y \
    dumb-init \
    libcurl4 \
    libgstreamer1.0-0 \
    gstreamer1.0-plugins-base \
    gstreamer1.0-plugins-good \
    libzmq5 \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder-audio /build/output/bin/odr-audioenc /usr/bin/

COPY --from=builder-pad /build/output/bin/odr-padenc /usr/bin/

COPY --chmod=0755 run.sh /run.sh

ENTRYPOINT ["dumb-init", "sh", "/run.sh"]
